# Generated by Django 4.0.6 on 2022-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenercore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='original_link',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
