# Generated by Django 4.0.6 on 2022-07-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenercore', '0003_remove_link_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_link',
            field=models.CharField(max_length=500),
        ),
    ]
