# Generated by Django 4.0.6 on 2022-07-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenercore', '0004_alter_link_original_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
